# Specific for https://geocity.ch/app
PRODUCTION_PATH=/app
#Must not be empty
LOCATION_API=
GEOCITY_API=https://geocity.ch/rest/
GEOCITY_API_EVENTS_START=2022-01-01
GEOCITY_API_EVENTS_END=2030-12-01
GEOCITY_API_ADMINISTRATIVE_ENTITES=
GEOCITY_API_SHOW_ONLY_FUTURE=false
CTA_LINK=https://geocity.ch
DEFAULT_VIEW='calendar'
DISPLAY_FOOTER_AND_HEADER=true
DEFAULT_CALENDAR_MODE='default'
MOCK=
